miniLibrary2017/Controllers/EditAuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using miniLibrary2017.Models;
using System.Configuration;
using System.Data.SqlClient;

namespace miniLibrary2017.Controllers
{
    public class EditAuthorController : Controller
    {
        DBminiLibrary db = new DBminiLibrary();
        // GET: EditAuthor
        public ActionResult Index()
        {
            var listAuthor = (from item in db.tabAuthor
                              orderby item.LastName
                              select item).ToList();
            return View(listAuthor);
        }

        // edycja i dodaj nowy
        [HttpGet]
        [Authorize]
        public ActionResult EditAuthor(int? id)
        {
            Author toEdit;
            if( id!= null) //sprawdzanie czy jest
            {
                toEdit = db.tabAuthor.Find(id);
                if (toEdit == null)
                    return new HttpNotFoundResult();
            }
            else //dodanie Autora
            {
                toEdit = new Author();
            }
            return View(toEdit);
        }
        //zwracanie po zmianie
        [HttpPost]
        [Authorize]
        public ActionResult EditAuthor(Author author)
        {
            if (ModelState.IsValid)
            {
                Author toEdit;
                if (author.Id == 0)
                {
                    toEdit = new Author();
                    db.tabAuthor.Add(author);
                }
                else
                {
                    toEdit = db.tabAuthor.Find(author.Id);
                    if(toEdit != null)
                    {
                        try
                        {
                            string CS = ConfigurationManager.ConnectionStrings["DBCS"].ConnectionString;
                            using (SqlConnection con = new SqlConnection(CS))
                            {
                                SqlCommand cmd = new SqlCommand("AuthorEdit", con);
                                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                                cmd.Parameters.AddWithValue("@Id", toEdit.Id);
                                cmd.Parameters.AddWithValue("@Fname", toEdit.FirstName);
                                cmd.Parameters.AddWithValue("@Lname", toEdit.LastName);
                                con.Open();
                                cmd.ExecuteNonQuery();
                            }
                        }
                        catch (Exception e)
                        {
                            Response.Write(e.Message);
                        }


                        toEdit.LastName = author.LastName;
                        toEdit.FirstName = author.FirstName;
                    }
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        //kasowanie Autora
        [HttpGet]
        [Authorize]
        public ActionResult DeleteAuthor(int id)
        {
            Author toDelete = db.tabAuthor.Find(id);
            if (toDelete == null)
                return new HttpNotFoundResult();
            return View(toDelete);
        }

        //zapis zakascji
        [HttpPost]
        [Authorize]
        public ActionResult DeleteAuthor(Author author)
        {
            Author toDelete = db.tabAuthor.Find(author.Id);
            if (toDelete != null)
            {
                try
                {
                    string CS = ConfigurationManager.ConnectionStrings["DBCS"].ConnectionString;
                    using (SqlConnection con = new SqlConnection(CS))
                    {
                        SqlCommand cmd = new SqlCommand("AuthorDelete", con);
                        cmd.CommandType = System.Data.CommandType.StoredProcedure;

                        cmd.Parameters.AddWithValue("@Id", toDelete.Id);

                        con.Open();
                        cmd.ExecuteNonQuery();
                    }
                }
                catch (Exception e)
                {
                    Response.Write(e.Message);
                }

                //db.tabAuthor.Remove(toDelete);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

miniLibrary2017/Controllers/EditBookController.cs
using miniLibrary2017.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Data.Entity;

namespace miniLibrary2017.Controllers
{
    public class EditBookController : Controller
    {
        
        DBminiLibrary db = new DBminiLibrary();
        // GET: EditBook
        public ActionResult Index()
        {

            var viewModel =(from bk in db.tabBook
            join ar in db.tabAuthor on bk.IdAuthor equals ar.Id        
            orderby bk.Title
            select new ViewBook { book = bk, author = ar }).ToList();
            return View(viewModel);


        }
        [Authorize]
        [HttpGet]
        public ActionResult EditBook(int? id)
        {
            Book toEdit;
            if (id != null)
            {
                toEdit = db.tabBook.Find(id);
                if (toEdit == null)
                    return new HttpNotFoundResult();
            }
            else
            {
                toEdit = new Models.Book();
                toEdit.YearOfPublish = DateTime.Now;
            }

            List<SelectListItem> listaZPoz0 = new List<SelectListItem>();
            listaZPoz0.Add(new SelectListItem { Text = "wybierz autora", Value = "" });
            List<SelectListItem> listaAutorow = (from item in db.tabAuthor
                                                 orderby item.LastName
                                                 select new SelectListItem { Value = item.Id.ToString(), Text = item.LastName +" "+ item.FirstName }).ToList();
            listaZPoz0.AddRange(listaAutorow);

            ViewBag.Autorzy = listaZPoz0;
            return View(toEdit);
        }

        //zapis do zmianie
        [Authorize]
        [HttpPost]
        public ActionResult EditBook(Book book)
        {
            if (ModelState.IsValid)
            {
                Book toEdit;
                if (book.Id == 0)
                {
                    toEdit = new Models.Book();
                    
                    db.tabBook.Add(book);
                    
                }
                else
                {
                    toEdit = db.tabBook.Find(book.Id);
                    if (toEdit != null)
                    {
                        try
                        {
                            string CS = ConfigurationManager.ConnectionStrings["DBCS"].ConnectionString;
                            using (SqlConnection con = new SqlConnection(CS))
                            {
                                SqlCommand cmd = new SqlCommand("BookEdit", con);
                                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                                cmd.Parameters.AddWithValue("@Id", toEdit.Id);
                                cmd.Parameters.AddWithValue("@Title", toEdit.Title);
                                cmd.Parameters.AddWithValue("@YearOfPublish", toEdit.YearOfPublish);
                                cmd.Parameters.AddWithValue("@ISBN", toEdit.ISBN);
                                cmd.Parameters.AddWithValue("@IdAuthor", toEdit.IdAuthor);

                                con.Open();
                                cmd.ExecuteNonQuery();
                            }
                        }
                        catch (Exception e)
                        {
                            Response.Write(e.Message);
                        }
                        toEdit.IdAuthor = book.IdAuthor;
                        toEdit.Title = book.Title;
                        toEdit.ISBN = book.ISBN;
                        toEdit.YearOfPublish = book.YearOfPublish;
                    }
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            List<SelectListItem> listaZPoz0 = new List<SelectListItem>();
            listaZPoz0.Add(new SelectListItem { Text = "wybierz autora", Value = "" });
            List<SelectListItem> listaAutorow = (from item in db.tabAuthor
                                                 orderby item.LastName
                                                 select new SelectListItem { Value = item.Id.ToString(), Text = item.LastName +" "+ item.FirstName}).ToList();
            listaZPoz0.AddRange(listaAutorow);

            ViewBag.Autorzy = listaZPoz0;
            return View();
        }

        //kasowanie książki
        [Authorize]
        [HttpGet]
        public ActionResult DeleteBook(int id)
        {
            Book toDelete = db.tabBook.Find(id);
            if (toDelete == null)
                return new HttpNotFoundResult();
            return View(toDelete);
        }
        [Authorize]
        [HttpPost]
        public ActionResult DeleteBook(Book book)
        {
            Book toDelete = db.tabBook.Find(book.Id);
            ///
            try
            {
                string CS = ConfigurationManager.ConnectionStrings["DBCS"].ConnectionString;
                using (SqlConnection con = new SqlConnection(CS))
                {
                    SqlCommand cmd = new SqlCommand("BookDelete", con);
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@Id", toDelete.Id);

                    con.Open();
                    cmd.ExecuteNonQuery();
                }
            } catch (Exception e)
            {
                Response.Write(e.Message);
            }
            ////
            //db.tabBook.Remove(toDelete);
            db.SaveChanges();
             return RedirectToAction("Index");
            
        }
    }
}

miniLibrary2017/Controllers/UserController.cs
using miniLibrary2017.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace miniLibrary2017.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(miniLibrary2017.Models.User user)
        {
            if (ModelState.IsValid)
            {
                if(IsValid(user.Login, user.Password))
                {
                    FormsAuthentication.SetAuthCookie(user.Login, false);
                   


                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Podane danę są nieprawidłowe.");
                }
            }
            

            return View(user);
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(miniLibrary2017.Models.User user)
        {
            if (ModelState.IsValid)
            {
                using (var db = new DBminiLibrary())
                {
                    var crypto = new SimpleCrypto.PBKDF2();

                    var entryPass = crypto.Compute(user.Password);
                    User sysUser = new User();
                    //var sysUser = db.tabUser.Create();

                    sysUser.Login = user.Login;
                    sysUser.Password = entryPass;
                    sysUser.PasswordSalt = crypto.Salt;

                    db.tabUser.Add(sysUser);
                    db.SaveChanges();

                    return RedirectToAction("Index", "Home");

                }
                
            }


            return View(user);
        }




        private bool IsValid(string login, string password)
        {
            var crypto = new SimpleCrypto.PBKDF2();

            bool isValid = false;

            using (var db = new DBminiLibrary())
            {
                var user = db.tabUser.FirstOrDefault(u => u.Login == login);

                if(user != null)
                {
                    if(user.Password == crypto.Compute(password, user.PasswordSalt))
                        {
                            isValid = true;
                        }
                }
            }

            return isValid;
        }
    }
}

miniLibrary2017/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
 
    <script>
  ( function( factory ) {
      if (typeof define === "function" && define.amd)
      {
        define( [ "../widgets/datepicker" ], factory );
      }
      else
      {
        factory( jQuery.datepicker );
    }
  }(function (datepicker)
  {

      datepicker.regional.pl =
          {
    closeText: "Zamknij",
    prevText: "&#x3C;Poprzedni",
    nextText: "Następny&#x3E;",
    currentText: "Dziś",
    monthNames: [ "Styczeń","Luty","Marzec","Kwiecień","Maj","Czerwiec",
    "Lipiec","Sierpień","Wrzesień","Październik","Listopad","Grudzień" ],
    monthNamesShort: [ "Sty","Lu","Mar","Kw","Maj","Cze",
    "Lip","Sie","Wrz","Pa","Lis","Gru" ],
    dayNames: [ "Niedziela","Poniedziałek","Wtorek","Środa","Czwartek","Piątek","Sobota" ],
    dayNamesShort: [ "Nie","Pn","Wt","Śr","Czw","Pt","So" ],
    dayNamesMin: [ "N","Pn","Wt","Śr","Cz","Pt","So" ],
    weekHeader: "Tydz",
    dateFormat: "yy-mm-dd",
    firstDay: 1,
    isRTL: false,
    showMonthAfterYear: false,
    yearSuffix: "" };
datepicker.setDefaults( datepicker.regional.pl );

return datepicker.regional.pl;

} ) );
      $(function() {
        $( "#datepicker" ).datepicker();
      });
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">

        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                    @Html.ActionLink("miniLibrary2017", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                     @Html.ActionLink("Lista Książek", "Index", "EditBook", new { area = "" }, new { @class = "navbar-brand" })
                      @Html.ActionLink("Lista Autorów", "Index", "EditAuthor", new { area = "" }, new { @class = "navbar-brand" })
                @if (User.Identity.Name == "admin")
                {
                    @Html.ActionLink("ShadowBook", "ShadowBook", "ShadowBook", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("ShadowAuthor", "ShadowAuthor", "ShadowAuthor", new { area = "" }, new { @class = "navbar-brand" })
                }

</div>
            @if (Request.IsAuthenticated)
            {
                <ul class="nav navbar-nav navbar-right">
                    <li><a href=@Url.Action("Logout", "User")><span class="glyphicon glyphicon-log-out"></span> Wyloguj</a></li>
                </ul>
            }
            else
            {
                <ul class="nav navbar-nav navbar-right">
                    <li><a href=@Url.Action("Register", "User")><span class="glyphicon glyphicon-user"></span>Rejestracja</a></li>
                    <li><a href=@Url.Action("Login", "User")><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                 </ul>
            }




            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
          
         
            @if (Request.IsAuthenticated)
            { <p>Zalogowany: @Html.Encode(User.Identity.Name) </p>}
            <p>&copy; @DateTime.Now.Year - miniLibrary Application - Adam Stajszczak &reg;</p>
        </footer>
    </div>


    @*<script src="~/Scripts/jquery-1.10.2.min.js"></script>*@
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>